function acknowledgement
% F=mfilename('fullpath');
% p=fileparts(F);
% 
% [im, map] = imread([p filesep 'postcard.gif']);

txt = {'Please acknowlegde SplitLab by citing our article:',...
' ',....
'Wüstefeld, A.; Bokelmann, G.H.R.; Zaroli, C.; Barruol, G.',...
'Splitlab - A Shear wave splitting environment in MatLab',...
'Computers and Geosciences 34(5):515-528 (2008)',...
'DOI:10.1016/j.cageo.2007.08.002'};
h=msgbox(txt,'Acknowlegdement','help','modal');
waitfor(h)
