%% callback function to provide a simple dialog box where user can enter a 
%  username and password in edit fields, confirm with one button or cancel
%  with the other
%  Rob Porritt, July 2014

function SL_addRestrictedDataParams

  global config;

% Get position of box
  p = get(0,'DefaultFigurePosition');
  p = [p(1) p(2) p(3) p(4)*.5];

  tmpConfig.restrictedAccessPassword = [];
  
  % Draw box
  restrictedParamsHandles = figure('Name','Restricted Params','Position',p,'Resize','off');
  panelHandles = uipanel('Parent',restrictedParamsHandles,'Units','pixel',...
    'Title','Restricted Data Access','FontSize',10,'Position',[10 10 p(3)*.95 p(4)*.9] ,... 
    'BackgroundColor', [224   223   227]/255 );
    

   % two edit boxes and text boxes
  textHandles1 =  uicontrol('Parent',panelHandles,'Units','pixel',...
    'Style','Text','FontSize',12,...
    'Position',[15 p(4)*.7 p(3)*.3 20],...
    'String', 'Enter your username:');   
  editHandles1 = uicontrol('Parent',panelHandles,'Units','pixel',...
    'Style','Edit','FontSize',12,...
    'BackgroundColor','w',...
    'Position',[p(3)*.32 p(4)*.7 p(3)*.50 20],...
    'String', config.restrictedAccessUserName,...
    'FontName','FixedWidth','ToolTipString','Input username for restricted data access',...
    'Callback','tmpConfig.restrictedAccessUserName=get(gcbo,''String'');');
    
textHandles2 =  uicontrol('Parent',panelHandles,'Units','pixel',...
    'Style','Text','FontSize',12,...
    'Position',[15 p(4)*.5 p(3)*.3 20],...
    'String', 'Enter your password:');   
  editHandles2 = uicontrol('Parent',panelHandles,'Units','pixel',...
    'Style','Edit','FontSize',12,...
    'BackgroundColor','w',...
    'Position',[p(3)*.32 p(4)*.5 p(3)*.50 20],...
    'String', '*',...
    'userdata', tmpConfig.restrictedAccessPassword,...
    'FontName','FixedWidth','ToolTipString','Input password for restricted data access',...
    'KeyPressFcn',{@keypress_hidePassword});
 %   'Callback','tmpConfig.restrictedAccessPassword=get(gcbo,''String'');');
 
   % three buttons

% Take the new entry
button1Handles = uicontrol('Parent',panelHandles,'Units','pixel',...
    'Style','pushbutton','FontSize',12,'String','Confirm',...
    'Position',[p(1)*.1  p(4)*.15 p(3)*0.2 40],...
    'Callback','config.restrictedAccessUserName = tmpConfig.restrictedAccessUserName; config.restrictedAccessPassword = get(findobj(''ToolTipString'',''Input password for restricted data access''),''userdata''); config.restrictedAccess{1} = config.restrictedAccessUserName; config.restrictedAccess{2} = config.restrictedAccessPassword; pause(0.1); close(gcf);');

% Keep existing info
button2Handles = uicontrol('Parent',panelHandles,'Units','pixel',...
    'Style','pushbutton','FontSize',12,'String','Cancel',...
    'Position',[p(3)*.26+p(1)*.1 p(4)*.15 p(3)*.20 40],...
    'Callback','config.restrictedAccess{1} = config.restrictedAccessUserName; config.restrictedAccess{2} = config.restrictedAccessPassword; pause(0.1); close(gcf);');

% Clear out (sorry this is probably really hard to read!)
button2Handles = uicontrol('Parent',panelHandles,'Units','pixel',...
                           'Style','pushbutton','FontSize',12,'String','Clear',...
                           'Position',[p(3)*.6+10 p(4)*.15 p(3)*.20 40],...
                           'Callback','config.restrictedAccessUserName = []; config.restrictedAccessPassword = []; config.restrictedAccess{1} = config.restrictedAccessUserName; config.restrictedAccess{2} = config.restrictedAccessPassword; pause(0.1); close(gcf);');


%set(restrictedParamsHandles,'KeyPressFcn',{@keypress_hidePassword,editHandles2});

function keypress_hidePassword(hObj, data)
    pass = get(hObj,'userdata');
    switch data.Key
        case 'backspace'
        pass = pass(1:end-1);
  %
    case 'return'
        uiresume
        return
  %
    otherwise
        pass = [pass data.Character];
    end
    set(hObj,'userdata',pass)
    set(hObj,'String',char('*'*sign(pass)))

    
                       
                       



